default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: username
      password: password
      host:     localhost

development:
  <<: *default
  database: ideaslist_development

test:
  <<: *default
  database: ideaslist_test

production:
  <<: *default
  database: ideaslist_production
